___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## Creating a Pandas Series

In [1]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [2]:
ser = [5,10,15,20,25]

In [3]:
ser

[5, 10, 15, 20, 25]

In [5]:
ser=pd.Series([5,10,15,20,25])

In [6]:
ser

0     5
1    10
2    15
3    20
4    25
dtype: int64

### Basic Attributes of Series

In [7]:
type(ser)

pandas.core.series.Series

In [8]:
ser.dtype

dtype('int64')

In [16]:
ser.size

5

In [17]:
ser.ndim

1

In [9]:
ser

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [10]:
ser.values

array([ 5, 10, 15, 20, 25], dtype=int64)

In [12]:
ser.head(2)

0     5
1    10
dtype: int64

In [13]:
ser.tail(1)

4    25
dtype: int64

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [14]:
labels = [i for i in 'python']
my_list = list(np.arange(6))
d = dict(zip(labels,my_list))

arr = np.array([10, 20, 30,40,50,60])


In [21]:
labels

['p', 'y', 't', 'h', 'o', 'n']

In [16]:
my_list

[0, 1, 2, 3, 4, 5]

In [22]:
d

{'p': 0, 'y': 1, 't': 2, 'h': 3, 'o': 4, 'n': 5}

### **Using Lists**

In [24]:
my_labels=pd.Series(labels)

In [25]:
my_labels

0    p
1    y
2    t
3    h
4    o
5    n
dtype: object

In [28]:
my_labels.values

array(['p', 'y', 't', 'h', 'o', 'n'], dtype=object)

In [30]:
my_list

[0, 1, 2, 3, 4, 5]

In [29]:
pd.Series(my_list)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [31]:
d

{'p': 0, 'y': 1, 't': 2, 'h': 3, 'o': 4, 'n': 5}

In [32]:
pd.Series(d)

p    0
y    1
t    2
h    3
o    4
n    5
dtype: int64

In [37]:
focus = {"harun":25,"emir":20,"gulchin":30}

In [38]:
focus

{'harun': 25, 'emir': 20, 'gulchin': 30}

In [40]:
a = pd.Series(focus)

In [41]:
a

harun      25
emir       20
gulchin    30
dtype: int64

In [42]:
a.shape

(3,)

In [43]:
a.ndim

1

In [44]:
a.size

3

In [46]:
a.values

array([25, 20, 30], dtype=int64)

### **Using NumPy Arrays**

p    10
y    20
t    30
h    40
o    50
n    60
dtype: int32

### **Using Dictionary**

p    0
y    1
t    2
h    3
o    4
n    5
dtype: int64

In [47]:
d

{'p': 0, 'y': 1, 't': 2, 'h': 3, 'o': 4, 'n': 5}

In [49]:
pd.Series(data = d, index = ["p","y","t","e"])

p    0
y    1
t    2
h    3
o    4
n    5
dtype: int64

In [50]:
pd.Series(data = d, index = ["p","y","t","e"])

p    0.0
y    1.0
t    2.0
e    NaN
dtype: float64

### Data in a Series

A pandas Series can hold a variety of object types:

In [72]:
pd.Series({1,2,3,6})

TypeError: 'set' type is unordered

In [68]:
pd.Series(set)

0    <class 'set'>
dtype: object

str, int, bool, np func, built in

In [76]:
pd.Series(['pandas', 5, False, np.mean, len])

0                                   pandas
1                                        5
2                                    False
3    <function mean at 0x000002F716EC05E0>
4                  <built-in function len>
dtype: object

***



## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [58]:
ser1 = pd.Series(index = ['numpy', 'pandas','sql', 'gss','scipy'], data=[1,2,3,4,5])                      

In [60]:
ser2 = pd.Series([1,2,5,4,6],index = ['numpy', 'pandas','tableau', 'seaborn','matplotlib'])

In [59]:
ser1

numpy     1
pandas    2
sql       3
gss       4
scipy     5
dtype: int64

In [61]:
ser2

numpy         1
pandas        2
tableau       5
seaborn       4
matplotlib    6
dtype: int64

In [62]:
ser1["numpy"]

1

In [63]:
ser2["numpy"]

1

In [64]:
ser2["seaborn"]

4

In [65]:
ser1

numpy     1
pandas    2
sql       3
gss       4
scipy     5
dtype: int64

In [66]:
ser2

numpy         1
pandas        2
tableau       5
seaborn       4
matplotlib    6
dtype: int64

Operations are then also done based off of index:

In [67]:
ser1 + ser2

gss           NaN
matplotlib    NaN
numpy         2.0
pandas        4.0
scipy         NaN
seaborn       NaN
sql           NaN
tableau       NaN
dtype: float64

In [69]:
ser1.add(ser2, fill_value=0) # ekstra

gss           4.0
matplotlib    6.0
numpy         2.0
pandas        4.0
scipy         5.0
seaborn       4.0
sql           3.0
tableau       5.0
dtype: float64

### Indexing Examples

In [70]:
np.random.seed(101)
a = np.array(np.random.randint(5,12,6))
panser = pd.Series(a)
panser

0     8
1     6
2    11
3    10
4     8
5     6
dtype: int32

In [93]:
np.random.seed(101)
a = np.array(np.random.randint(5,12,6))
a

array([ 8,  6, 11, 10,  8,  6])

In [94]:
panser = pd.Series(a)

In [95]:
panser

0     8
1     6
2    11
3    10
4     8
5     6
dtype: int32

In [97]:
panser[0:2]

0    8
1    6
dtype: int32

0    8
1    6
dtype: int32

### pandas_series[index] | pandas_series[[indices, indices...]]

In [98]:
panser = pd.Series(data = [25, 32, 35, 33], index = ["terry", "micheal", "orion", "jason"])
panser

terry      25
micheal    32
orion      35
jason      33
dtype: int64

In [100]:
panser[2]

35

In [101]:
panser["jason"]

33

In [104]:
index1 = [0,1,3]

In [105]:
index1

[0, 1, 3]

In [112]:
panser[[0,3]]

terry    25
jason    33
dtype: int64

In [109]:
panser

terry      25
micheal    32
orion      35
jason      33
dtype: int64

In [111]:
panser["terry": "orion"]

terry      25
micheal    32
orion      35
dtype: int64

In [116]:
panser[:3]

terry      25
micheal    32
orion      35
dtype: int64

In [ ]:
panser[ : ]

terry      121
micheal    200
orion      150
dtype: int64

In [117]:
panser.size

4

In [121]:
panser.ndim

1

### Several Selecting Attributes

In [122]:
panser

terry      25
micheal    32
orion      35
jason      33
dtype: int64

In [123]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [126]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [ ]:
panser.

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [124]:
panser.values

array([25, 32, 35, 33], dtype=int64)

array([25, 32, 35, 33], dtype=int64)

In [128]:
panser.items()

In [129]:
list(panser.items())

[('terry', 25), ('micheal', 32), ('orion', 35), ('jason', 33)]

In [130]:
panser

terry      25
micheal    32
orion      35
jason      33
dtype: int64

In [131]:
'jackson' in panser

False

In [135]:
"jason" in panser.values

<ipython-input-135-2aafa82aed1d>:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  "jason" in panser.values


False

In [137]:
25 in panser.values

True

In [138]:
panser

terry      25
micheal    32
orion      35
jason      33
dtype: int64

In [141]:
panser["terry"] = 99

In [142]:
panser

terry      99
micheal    32
orion      35
jason      33
dtype: int64

In [143]:
panser

terry      99
micheal    32
orion      35
jason      33
dtype: int64

In [146]:
panser>40

terry       True
micheal    False
orion      False
jason      False
dtype: bool

In [145]:
panser[panser > 40]

terry    99
dtype: int64

In [147]:
panser>32

terry       True
micheal    False
orion       True
jason       True
dtype: bool

In [148]:
panser[(panser > 32)]

terry    99
orion    35
jason    33
dtype: int64

DataFrames

In [155]:
harun = pd.Series(data = [11,12,13,14], index = ["a","b","c","d"])

In [156]:
harun

a    11
b    12
c    13
d    14
dtype: int64

In [157]:
harun = pd.DataFrame(data = harun, columns= ["yaşlar"])

In [158]:
harun

yaşlar
a      11
b      12
c      13
d      14

In [159]:
data = np.arange(1,21,4)

In [160]:
data

array([ 1,  5,  9, 13, 17])

In [161]:
pd.Series(data)

0     1
1     5
2     9
3    13
4    17
dtype: int32

In [162]:
pd.DataFrame(data, columns=['column1'])

column1
0        1
1        5
2        9
3       13
4       17

In [163]:
data2 = np.arange(1,18,2).reshape(3,3)

In [167]:
data2 = np.arange(1,18,2).reshape(3,3)
data2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [177]:
group = pd.DataFrame(data = data2, index = ["a","b","c"], columns = ["emir","gulchin","harun"])

In [178]:
group

emir  gulchin  harun
a     1        3      5
b     7        9     11
c    13       15     17

In [179]:
group.index

Index(['a', 'b', 'c'], dtype='object')

In [169]:
data2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [170]:
df3=pd.DataFrame(data2, columns=['var1', 'var2', 'var3'])
df3

var1  var2  var3
0     1     3     5
1     7     9    11
2    13    15    17

In [171]:
df3.shape

(3, 3)

In [172]:
df3.size

9

In [173]:
df3.ndim

2

In [174]:
df3

var1  var2  var3
0     1     3     5
1     7     9    11
2    13    15    17

In [175]:
df3.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [176]:
df3.index

RangeIndex(start=0, stop=3, step=1)

In [180]:
df3

var1  var2  var3
0     1     3     5
1     7     9    11
2    13    15    17

In [181]:
df3.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [182]:
df3.columns = ["new1","new","new3"]

In [183]:
df3

new1  new  new3
0     1    3     5
1     7    9    11
2    13   15    17

In [188]:
df3.index = ["emir","clarusway","abcd"]

In [189]:
df3

new1  new  new3
emir          1    3     5
clarusway     7    9    11
abcd         13   15    17

for your info:

* 1 dim --> vector 
* 2 dim --> matrix
* 3 dim --> tensor

 - ### Creating a DataFrame using a ``NumPy Arrays``

In [194]:
m=np.arange(1,50,5).reshape(5,2)
m

array([[ 1,  6],
       [11, 16],
       [21, 26],
       [31, 36],
       [41, 46]])

In [195]:
df=pd.DataFrame(m, columns=['col1','col2'])
df

col1  col2
0     1     6
1    11    16
2    21    26
3    31    36
4    41    46

In [218]:
df.sample(5)

col1  col2
2    21    26
1    11    16
4    41    46
0     1     6
3    31    36

col1  col2
2    21    26
1    11    16

 - ### Creating a DataFrame using a ``dict``

In [219]:
np.random.seed(101)
s1 = np.random.randint(10,18, size = 4)
s2 = np.random.randint(19,27, size = 4)
s3 = np.random.randint(28,35, size = 4)

In [225]:
s1

array([17, 13, 11, 16])

In [221]:
s2

array([26, 26, 24, 22])

In [222]:
s3

array([29, 33, 28, 32])

In [226]:
myDict= {'var1':s1,'var2':s2,'var3':s3}

In [227]:
myDict

{'var1': array([17, 13, 11, 16]),
 'var2': array([26, 26, 24, 22]),
 'var3': array([29, 33, 28, 32])}

In [228]:
df1 = pd.DataFrame(myDict)

In [232]:
df1

var1  var2  var3
0    17    26    29
1    13    26    33
2    11    24    28
3    16    22    32

In [234]:
np.arange(10,50,10)

array([10, 20, 30, 40])

In [235]:
sözlük = {"key1":np.arange(0,4,1), "key2": np.arange(10,50,10)}

In [236]:
sözlük

{'key1': array([0, 1, 2, 3]), 'key2': array([10, 20, 30, 40])}

In [238]:
pd.DataFrame(data=sözlük, index = ["a","b","c","d"])

key1  key2
a     0    10
b     1    20
c     2    30
d     3    40

- Simple indexing and slicing the ``DataFrames``

In [243]:
df1

var1  var2  var3
0    17    26    29
1    13    26    33
2    11    24    28
3    16    22    32

In [245]:
df1[1:3]

var1  var2  var3
1    13    26    33
2    11    24    28

In [246]:
df1

var1  var2  var3
0    17    26    29
1    13    26    33
2    11    24    28
3    16    22    32

In [247]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [248]:
df1.index = ["a","b","c","d"]

In [249]:
df1

var1  var2  var3
a    17    26    29
b    13    26    33
c    11    24    28
d    16    22    32

In [250]:
df1

var1  var2  var3
a    17    26    29
b    13    26    33
c    11    24    28
d    16    22    32

In [251]:
df1["b":"d"]

var1  var2  var3
b    13    26    33
c    11    24    28
d    16    22    32

In [256]:
df1[1:]

var1  var2  var3
b    13    26    33
c    11    24    28
d    16    22    32

In [260]:
# we can check any column name whether it belongs to the DataFrame or not
"var2" in df1

True

In [261]:
'var5' in df1

False

### Now, let's examine again the ***idexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [2]:
from numpy.random import randn
np.random.seed(101)

In [3]:
# creating a DataFrame by "keyword arguments"
df3=pd.DataFrame(randn(5,4),columns='w x y z'.split(), index='a b c d e'.split())
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [10]:
df3[["y"]]

y
a  0.907969
b -0.848077
c  0.528813
d -0.933237
e  2.605967

In [12]:
type(df3[["y"]])

pandas.core.frame.DataFrame

#### DataFrame Columns are just Series

In [13]:
df3["y"]

a    0.907969
b   -0.848077
c    0.528813
d   -0.933237
e    2.605967
Name: y, dtype: float64

In [14]:
df3[["y"]]

y
a  0.907969
b -0.848077
c  0.528813
d -0.933237
e  2.605967

In [15]:
# Pass a list of column names
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [18]:
df3[["w","x"]]

w         x
a  2.706850  0.628133
b  0.651118 -0.319318
c -2.018168  0.740122
d  0.188695 -0.758872
e  0.190794  1.978757

w         y
a  0.386030 -0.376519
b  0.681209 -0.031160
c -1.005187  0.187125
d -1.382920  0.961458
e  0.992573 -1.046780

In [19]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [21]:
df3[0:3]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001

In [ ]:
loc (label) / iloc (index)

In [27]:
df3.iloc[0:2]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965

**Creating a new column:**

In [28]:

df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [29]:
df3["w+z"] = df3["w"]+df3["z"]

In [30]:
df3

w         x         y         z       w+z
a  2.706850  0.628133  0.907969  0.503826  3.210676
b  0.651118 -0.319318 -0.848077  0.605965  1.257083
c -2.018168  0.740122  0.528813 -0.589001 -2.607169
d  0.188695 -0.758872 -0.933237  0.955057  1.143752
e  0.190794  1.978757  2.605967  0.683509  0.874303

In [33]:
df3 = df3.drop("w+z", axis = 1)

In [34]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

w         x         y         z       w+z
a  2.706850  0.628133  0.907969  0.503826  3.210676
b  0.651118 -0.319318 -0.848077  0.605965  1.257083
c -2.018168  0.740122  0.528813 -0.589001 -2.607169
d  0.188695 -0.758872 -0.933237  0.955057  1.143752
e  0.190794  1.978757  2.605967  0.683509  0.874303

 - ### Removing Columns

In [179]:
# Not inplace unless specified!


In [180]:
df3

w         x         y         z
a  0.386030  2.084019 -0.376519  0.230336
b  0.681209  1.035125 -0.031160  1.939932
c -1.005187 -0.741790  0.187125 -0.732845
d -1.382920  1.482495  0.961458 -2.141212
e  0.992573  1.192241 -1.046780  1.292765

 - ### Removing rows

In [35]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [36]:
# the default value of axis is 0 (axis = 0)
df4 = df3.drop("c",axis=0)

In [37]:
df4

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [38]:
df4

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [39]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [40]:
df4 = df4.append(df3.loc["a"])

In [41]:
df4

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509
a  2.706850  0.628133  0.907969  0.503826

In [45]:
df4

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509
a  2.706850  0.628133  0.907969  0.503826

### Selecting Rows

- ### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [46]:
np.random.seed(101)
m=np.random.randint(1,20, size=(5,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0    12    18     7    12
1    16    10    14     9
2     5     9     1    15
3     6    13     9    18
4    16     9     3    13

In [53]:
df4.loc[4]

var1    16
var2     9
var3     3
var4    13
Name: 4, dtype: int32

In [55]:
df4.loc[2:3]

var1  var2  var3  var4
2     5     9     1    15
3     6    13     9    18

In [56]:
df4

var1  var2  var3  var4
0    12    18     7    12
1    16    10    14     9
2     5     9     1    15
3     6    13     9    18
4    16     9     3    13

In [57]:
df4.iloc[4]

var1    16
var2     9
var3     3
var4    13
Name: 4, dtype: int32

var1    16
var2     9
var3     3
var4    13
Name: 4, dtype: int32

In [59]:
# Slicing produces the same type of the data. Here, DataFrame
df4.iloc[2:5]

var1  var2  var3  var4
2     5     9     1    15
3     6    13     9    18
4    16     9     3    13

var1  var2  var3  var4
2     5     9     1    15
3     6    13     9    18
4    16     9     3    13

In [60]:
df4

var1  var2  var3  var4
0    12    18     7    12
1    16    10    14     9
2     5     9     1    15
3     6    13     9    18
4    16     9     3    13

In [62]:
df4.index = ["a","b","c","d","e"]

In [63]:
df4

var1  var2  var3  var4
a    12    18     7    12
b    16    10    14     9
c     5     9     1    15
d     6    13     9    18
e    16     9     3    13

In [ ]:

df4

In [64]:
df4

var1  var2  var3  var4
a    12    18     7    12
b    16    10    14     9
c     5     9     1    15
d     6    13     9    18
e    16     9     3    13

In [67]:
df4.loc[["b","c","d"]]

var1  var2  var3  var4
b    16    10    14     9
c     5     9     1    15
d     6    13     9    18

In [68]:
df4.iloc[1:4]

var1  var2  var3  var4
b    16    10    14     9
c     5     9     1    15
d     6    13     9    18

var1  var2  var3  var4
b    16    10    14     9
c     5     9     1    15
d     6    13     9    18

var1  var2  var3  var4
b    16    10    14     9
c     5     9     1    15
d     6    13     9    18
e    16     9     3    13

In [69]:
df4

var1  var2  var3  var4
a    12    18     7    12
b    16    10    14     9
c     5     9     1    15
d     6    13     9    18
e    16     9     3    13

In [73]:
df4.loc["b":"e", "var3"]

b    14
c     1
d     9
e     3
Name: var3, dtype: int32

In [75]:
df4.loc["b":"e"]["var3"]

b    14
c     1
d     9
e     3
Name: var3, dtype: int32

b    14
c     1
d     9
e     3
Name: var3, dtype: int32

In [83]:
# how can we select these data as a DataFrame not a series
df4[["var2"]].loc["b":"d"]

var2
b    10
c     9
d    13

var2
b    10
c     9
d    13

c    1
d    9
e    3
Name: var3, dtype: int32

var3
c     1
d     9
e     3

In [222]:
df3.loc['c']

w   -1.005187
x   -0.741790
y    0.187125
z   -0.732845
Name: c, dtype: float64

In [86]:
df3.loc[["c"]]

w         x         y         z
c -2.018168  0.740122  0.528813 -0.589001

In [89]:
df3[:].loc[["c"]]

w         x         y         z
c -2.018168  0.740122  0.528813 -0.589001

w        x         y         z
c -1.005187 -0.74179  0.187125 -0.732845

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

In [90]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [94]:
df3.loc[["c"]][["y"]]

y
c  0.528813

In [95]:
df3.loc[["c"],["y"]]

y
c  0.528813

In [98]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [106]:
df3.loc[["b"],["x"]]["x"].values

array([-0.31931804])

-1.005186917256266

In [ ]:
# let's select the same data as a DataFrame


w
c -1.005187

In [107]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [113]:
df3.loc["c":"e","w":"z"]

w         x         y         z
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

w         z
c -1.005187 -0.732845
e  0.992573  1.292765

w         z
c -2.018168 -0.589001
e  0.190794  0.683509

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [121]:
df3[(df3>0.6)|(df3<0.2)]

w         x         y         z
a  2.706850  0.628133  0.907969       NaN
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122       NaN -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [231]:
df3[df3>0.2]

w         x         y         z
a  0.386030  2.084019       NaN  0.230336
b  0.681209  1.035125       NaN  1.939932
c       NaN       NaN       NaN       NaN
d       NaN  1.482495  0.961458       NaN
e  0.992573  1.192241       NaN  1.292765

In [122]:
df3['y']<0.5

a    False
b     True
c    False
d     True
e    False
Name: y, dtype: bool

In [123]:
# It returns based on rows.
df3[df3['y']<0.5]

w         x         y         z
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057

In [124]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [125]:
df3[df3['w']<1][['z','y']]

z         y
b  0.605965 -0.848077
c -0.589001  0.528813
d  0.955057 -0.933237
e  0.683509  2.605967

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

In [126]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [237]:
df3[(df3['w']>0) & (df3['z']<1)]  # df[(cond1)&(cond2)&(cond3)] --> cond1 df["harun"] == "pazar"

w         x         y         z
a  0.38603  2.084019 -0.376519  0.230336

#### Conditional selection using ``.loc[]`` and ``.iloc[]``

In [134]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [136]:
df3.y  # df3["y"]

a    0.907969
b   -0.848077
c    0.528813
d   -0.933237
e    2.605967
Name: y, dtype: float64

In [138]:
(df3["y"]>0)

a     True
b    False
c     True
d    False
e     True
Name: y, dtype: bool

In [144]:
df3.loc[["w","z"](df3["y"]>0),]

w         z
a  2.706850  0.503826
c -2.018168 -0.589001
e  0.190794  0.683509

In [145]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [159]:
df3.loc[df3.w>2, ["y"]]

y
a  0.907969

In [133]:
df3.loc[(df3.y>0), ['w','z']]

w         z
a  2.706850  0.503826
c -2.018168 -0.589001
e  0.190794  0.683509

In [240]:
df3.loc[((df3.x>1) | (df3.y<1)), ['x','w']]

x         w
a  2.084019  0.386030
b  1.035125  0.681209
c -0.741790 -1.005187
d  1.482495 -1.382920
e  1.192241  0.992573

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [241]:
df3

w         x         y         z
a  0.386030  2.084019 -0.376519  0.230336
b  0.681209  1.035125 -0.031160  1.939932
c -1.005187 -0.741790  0.187125 -0.732845
d -1.382920  1.482495  0.961458 -2.141212
e  0.992573  1.192241 -1.046780  1.292765

In [ ]:
# Reset to default 0,1...n index


index         w         x         y         z
0     a  0.386030  2.084019 -0.376519  0.230336
1     b  0.681209  1.035125 -0.031160  1.939932
2     c -1.005187 -0.741790  0.187125 -0.732845
3     d -1.382920  1.482495  0.961458 -2.141212
4     e  0.992573  1.192241 -1.046780  1.292765

w         x         y         z
0  0.386030  2.084019 -0.376519  0.230336
1  0.681209  1.035125 -0.031160  1.939932
2 -1.005187 -0.741790  0.187125 -0.732845
3 -1.382920  1.482495  0.961458 -2.141212
4  0.992573  1.192241 -1.046780  1.292765

In [244]:
newindx='CA NY WY OR CO'.split()
newindx

['CA', 'NY', 'WY', 'OR', 'CO']

In [246]:
df3

w         x         y         z newidx
a  0.386030  2.084019 -0.376519  0.230336     CA
b  0.681209  1.035125 -0.031160  1.939932     NY
c -1.005187 -0.741790  0.187125 -0.732845     WY
d -1.382920  1.482495  0.961458 -2.141212     OR
e  0.992573  1.192241 -1.046780  1.292765     CO

In [249]:
df3

w         x         y         z
newidx                                        
CA      0.386030  2.084019 -0.376519  0.230336
NY      0.681209  1.035125 -0.031160  1.939932
WY     -1.005187 -0.741790  0.187125 -0.732845
OR     -1.382920  1.482495  0.961458 -2.141212
CO      0.992573  1.192241 -1.046780  1.292765

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [255]:
# Index Levels
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2','M3', 'M3', 'M3']
inside = [1, 2, 3, 1, 2, 3, 5, 6, 7]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1),
 ('M1', 2),
 ('M1', 3),
 ('M2', 1),
 ('M2', 2),
 ('M2', 3),
 ('M3', 5),
 ('M3', 6),
 ('M3', 7)]

In [256]:
hier_index=pd.MultiIndex.from_tuples(multi_index)

In [257]:
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           )

In [259]:
df5=pd.DataFrame(np.random.randn(9,4), index = hier_index, columns=['A','B','C','D'])
df5

A         B         C         D
M1 1 -2.288978  0.441018  0.656973  0.136999
   2 -0.451982 -1.094163 -0.006354 -1.403832
   3 -0.202026 -1.089143  1.406601  1.577691
M2 1  0.545812 -0.693707 -0.389968 -0.170756
   2 -0.703198  2.067214  0.455452 -1.123753
   3 -1.088266 -0.609936 -0.635511 -0.728053
M3 5 -0.594951 -0.593371  0.911416 -1.768073
   6  0.205247  0.211945 -1.240039  1.049300
   7 -0.410414  0.340754  0.805027  0.528188

Now let's show how to index this! For index hierarchy we use ``df.loc[]``, if this was on the columns axis, you would just use normal bracket notation ``df[]``. Calling one level of the index returns the sub-dataframe:

A         B         C         D
Num                                        
5   -0.594951 -0.593371  0.911416 -1.768073
6    0.205247  0.211945 -1.240039  1.049300
7   -0.410414  0.340754  0.805027  0.528188

In [274]:
df5.loc['M2'].loc[2]

A   -0.703198
B    2.067214
C    0.455452
D   -1.123753
Name: 2, dtype: float64

A         B         C         D
Num                                        
2   -0.703198  2.067214  0.455452 -1.123753

In [262]:
df5.index.names

FrozenList([None, None])

In [263]:
df5.index.names = ['Group','Num']

In [264]:
df5

A         B         C         D
Group Num                                        
M1    1   -2.288978  0.441018  0.656973  0.136999
      2   -0.451982 -1.094163 -0.006354 -1.403832
      3   -0.202026 -1.089143  1.406601  1.577691
M2    1    0.545812 -0.693707 -0.389968 -0.170756
      2   -0.703198  2.067214  0.455452 -1.123753
      3   -1.088266 -0.609936 -0.635511 -0.728053
M3    5   -0.594951 -0.593371  0.911416 -1.768073
      6    0.205247  0.211945 -1.240039  1.049300
      7   -0.410414  0.340754  0.805027  0.528188

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-xs.ipynb)

A         B         C         D
Num                                        
5   -0.594951 -0.593371  0.911416 -1.768073
6    0.205247  0.211945 -1.240039  1.049300
7   -0.410414  0.340754  0.805027  0.528188

A         B         C         D
Num                                        
5   -0.594951 -0.593371  0.911416 -1.768073
6    0.205247  0.211945 -1.240039  1.049300
7   -0.410414  0.340754  0.805027  0.528188

In [267]:
df5

A         B         C         D
Group Num                                        
M1    1   -2.288978  0.441018  0.656973  0.136999
      2   -0.451982 -1.094163 -0.006354 -1.403832
      3   -0.202026 -1.089143  1.406601  1.577691
M2    1    0.545812 -0.693707 -0.389968 -0.170756
      2   -0.703198  2.067214  0.455452 -1.123753
      3   -1.088266 -0.609936 -0.635511 -0.728053
M3    5   -0.594951 -0.593371  0.911416 -1.768073
      6    0.205247  0.211945 -1.240039  1.049300
      7   -0.410414  0.340754  0.805027  0.528188

A   -0.703198
B    2.067214
C    0.455452
D   -1.123753
Name: (M2, 2), dtype: float64

A         B         C         D
Group                                        
M1    -0.202026 -1.089143  1.406601  1.577691
M2    -1.088266 -0.609936 -0.635511 -0.728053

A         B         C         D
Group                                        
M1    -0.202026 -1.089143  1.406601  1.577691
M2    -1.088266 -0.609936 -0.635511 -0.728053

In [272]:
df5.xs('A',axis=1)

Group  Num
M1     1     -2.288978
       2     -0.451982
       3     -0.202026
M2     1      0.545812
       2     -0.703198
       3     -1.088266
M3     5     -0.594951
       6      0.205247
       7     -0.410414
Name: A, dtype: float64